copyright = "©Tasin Tausif"
baseURL = ''
defaultContentLanguage = "en"
disableKinds = ["taxonomy"]
enableRobotsTXT = true
timeZone = "Europe/Berlin"
timeout = "120s"
languageCode = 'en-us'
title = 'HHCorporation'
theme = 'gallery'

[menu]

  [[menu.main]]
    identifier = 'about'
    name = 'About Us'
    url = '/about/'
    weight = 10

[params]
  defaultTheme = "dark"
  title = "HH Corporation"

  [params.author]
    email = "user@example.com"
    name = "Tasin Tausif"

  [params.socialIcons]
    facebook = "https://www.facebook.com/"
    instagram = "https://www.instagram.com/"
    github = "https://github.com/nicokaiser/hugo-theme-gallery/"
    youtube = "https://www.youtube.com/"
    email = "mailto:user@example.com"
    #website = "https://example.com"
    #mastodon = "https://example.com"
    #pixelfed = "https://example.com"
    #mixcloud = "https://mixcloud.com"

  [[menu.footer]]
    name = "Support"
    url = "https://github.com/nicokaiser/hugo-theme-gallery/"
    weight = 3
